# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Main CI

on:
  pull_request:
    branches: 
      - main
      - develop
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      act:
        image: lucasalt/act_base:latest
        ports:
        - 8545:8545
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Clone repos
        run: |
          cd ..
          git clone https://github.com/0xPolygonHermez/zkevm-testvectors.git --branch v2.0.0-fork.5
          cd zkevm-testvectors/tools/ethereum-tests
          git clone https://github.com/0xPolygonHermez/ethereum-tests tests
          cd tests
          git checkout test-vectors
          cd ../../../../zkevm-proverjs
      - name: setup zkevm-proverjs
        run: |
          npm i
      - name: Run full tracer tests
        run: |
          chmod -R 777 tools
          npm run test:full-tracer
      - name: eslint:tracer
        run: npm run eslint:tracer